language: node_js
node_js:
  - "8"
  - "8.10.0"
  - "6"
  - "6.13.1"
  - stable

install:
  - npm install

script: 
  - npm test

after_script:
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"